# Generated by Django 4.1.7 on 2023-03-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='firstname',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
