# Generated by Django 4.1.7 on 2023-03-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpostadmin_blogpost_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostAdmin',
        ),
    ]
